GPU: '0'
b1: 0.5
b2: 0.999
batch_size: 1
datasets_path: /work/classic/fr_hc1022-preprocess/train_data2/
fmap: 32
gap_t: 510
gap_x: 90
gap_y: 90
lr: 5.0e-05
n_epochs: 20
output_dir: ./results
overlap_factor: 0.4
patch_t: 150
patch_x: 150
patch_y: 150
pth_path: ./pth/train_data2_202601190035
scale_factor: 1
select_img_num: 1000000
train_datasets_size: 6000
